// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// load from file
type NodeMeta struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Tag                  string   `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Group                string   `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeMeta) Reset()         { *m = NodeMeta{} }
func (m *NodeMeta) String() string { return proto.CompactTextString(m) }
func (*NodeMeta) ProtoMessage()    {}
func (*NodeMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *NodeMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMeta.Unmarshal(m, b)
}
func (m *NodeMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMeta.Marshal(b, m, deterministic)
}
func (m *NodeMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMeta.Merge(m, src)
}
func (m *NodeMeta) XXX_Size() int {
	return xxx_messageInfo_NodeMeta.Size(m)
}
func (m *NodeMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMeta.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMeta proto.InternalMessageInfo

func (m *NodeMeta) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *NodeMeta) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *NodeMeta) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *NodeMeta) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *NodeMeta) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *NodeMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeMeta) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type UpdateRequest struct {
	PubName              string      `protobuf:"bytes,1,opt,name=pub_name,json=pubName,proto3" json:"pub_name,omitempty"`
	PubUsername          string      `protobuf:"bytes,2,opt,name=pub_username,json=pubUsername,proto3" json:"pub_username,omitempty"`
	PubPwd               string      `protobuf:"bytes,3,opt,name=pub_pwd,json=pubPwd,proto3" json:"pub_pwd,omitempty"`
	PubPort              int32       `protobuf:"varint,4,opt,name=pub_port,json=pubPort,proto3" json:"pub_port,omitempty"`
	PubGroup_            string      `protobuf:"bytes,5,opt,name=pub_group_,json=pubGroup,proto3" json:"pub_group_,omitempty"`
	PubTag               string      `protobuf:"bytes,6,opt,name=pub_tag,json=pubTag,proto3" json:"pub_tag,omitempty"`
	AuthorityUser        string      `protobuf:"bytes,7,opt,name=authority_user,json=authorityUser,proto3" json:"authority_user,omitempty"`
	NodeMetas            []*NodeMeta `protobuf:"bytes,8,rep,name=node_metas,json=nodeMetas,proto3" json:"node_metas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetPubName() string {
	if m != nil {
		return m.PubName
	}
	return ""
}

func (m *UpdateRequest) GetPubUsername() string {
	if m != nil {
		return m.PubUsername
	}
	return ""
}

func (m *UpdateRequest) GetPubPwd() string {
	if m != nil {
		return m.PubPwd
	}
	return ""
}

func (m *UpdateRequest) GetPubPort() int32 {
	if m != nil {
		return m.PubPort
	}
	return 0
}

func (m *UpdateRequest) GetPubGroup_() string {
	if m != nil {
		return m.PubGroup_
	}
	return ""
}

func (m *UpdateRequest) GetPubTag() string {
	if m != nil {
		return m.PubTag
	}
	return ""
}

func (m *UpdateRequest) GetAuthorityUser() string {
	if m != nil {
		return m.AuthorityUser
	}
	return ""
}

func (m *UpdateRequest) GetNodeMetas() []*NodeMeta {
	if m != nil {
		return m.NodeMetas
	}
	return nil
}

type Response struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Group                string   `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type DeleteRequest struct {
	Groups               []string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *DeleteRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type DeleteResponse struct {
	Response             []*Response `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetResponse() []*Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type UpdateResponse struct {
	Response             []*Response `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetResponse() []*Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type CacheRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheRequest) Reset()         { *m = CacheRequest{} }
func (m *CacheRequest) String() string { return proto.CompactTextString(m) }
func (*CacheRequest) ProtoMessage()    {}
func (*CacheRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *CacheRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheRequest.Unmarshal(m, b)
}
func (m *CacheRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheRequest.Marshal(b, m, deterministic)
}
func (m *CacheRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheRequest.Merge(m, src)
}
func (m *CacheRequest) XXX_Size() int {
	return xxx_messageInfo_CacheRequest.Size(m)
}
func (m *CacheRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CacheRequest proto.InternalMessageInfo

func (m *CacheRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CacheResponse struct {
	Response             int32    `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheResponse) Reset()         { *m = CacheResponse{} }
func (m *CacheResponse) String() string { return proto.CompactTextString(m) }
func (*CacheResponse) ProtoMessage()    {}
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *CacheResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheResponse.Unmarshal(m, b)
}
func (m *CacheResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheResponse.Marshal(b, m, deterministic)
}
func (m *CacheResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheResponse.Merge(m, src)
}
func (m *CacheResponse) XXX_Size() int {
	return xxx_messageInfo_CacheResponse.Size(m)
}
func (m *CacheResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CacheResponse proto.InternalMessageInfo

func (m *CacheResponse) GetResponse() int32 {
	if m != nil {
		return m.Response
	}
	return 0
}

type QueryRequest struct {
	GroupNames           []string `protobuf:"bytes,1,rep,name=group_names,json=groupNames,proto3" json:"group_names,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetGroupNames() []string {
	if m != nil {
		return m.GroupNames
	}
	return nil
}

func (m *QueryRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type QueryResponse struct {
	GroupMetas           map[string]int32 `protobuf:"bytes,1,rep,name=group_metas,json=groupMetas,proto3" json:"group_metas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	NodeMetas            []*NodeMeta      `protobuf:"bytes,2,rep,name=node_metas,json=nodeMetas,proto3" json:"node_metas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetGroupMetas() map[string]int32 {
	if m != nil {
		return m.GroupMetas
	}
	return nil
}

func (m *QueryResponse) GetNodeMetas() []*NodeMeta {
	if m != nil {
		return m.NodeMetas
	}
	return nil
}

type DumpRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpRequest) Reset()         { *m = DumpRequest{} }
func (m *DumpRequest) String() string { return proto.CompactTextString(m) }
func (*DumpRequest) ProtoMessage()    {}
func (*DumpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *DumpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpRequest.Unmarshal(m, b)
}
func (m *DumpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpRequest.Marshal(b, m, deterministic)
}
func (m *DumpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpRequest.Merge(m, src)
}
func (m *DumpRequest) XXX_Size() int {
	return xxx_messageInfo_DumpRequest.Size(m)
}
func (m *DumpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpRequest proto.InternalMessageInfo

func (m *DumpRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type DumpResponse struct {
	Response             int32    `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpResponse) Reset()         { *m = DumpResponse{} }
func (m *DumpResponse) String() string { return proto.CompactTextString(m) }
func (*DumpResponse) ProtoMessage()    {}
func (*DumpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *DumpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpResponse.Unmarshal(m, b)
}
func (m *DumpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpResponse.Marshal(b, m, deterministic)
}
func (m *DumpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpResponse.Merge(m, src)
}
func (m *DumpResponse) XXX_Size() int {
	return xxx_messageInfo_DumpResponse.Size(m)
}
func (m *DumpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DumpResponse proto.InternalMessageInfo

func (m *DumpResponse) GetResponse() int32 {
	if m != nil {
		return m.Response
	}
	return 0
}

func (m *DumpResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BasicRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicRequest) Reset()         { *m = BasicRequest{} }
func (m *BasicRequest) String() string { return proto.CompactTextString(m) }
func (*BasicRequest) ProtoMessage()    {}
func (*BasicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *BasicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicRequest.Unmarshal(m, b)
}
func (m *BasicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicRequest.Marshal(b, m, deterministic)
}
func (m *BasicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicRequest.Merge(m, src)
}
func (m *BasicRequest) XXX_Size() int {
	return xxx_messageInfo_BasicRequest.Size(m)
}
func (m *BasicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BasicRequest proto.InternalMessageInfo

func (m *BasicRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type BasicResponse struct {
	Response             int32    `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicResponse) Reset()         { *m = BasicResponse{} }
func (m *BasicResponse) String() string { return proto.CompactTextString(m) }
func (*BasicResponse) ProtoMessage()    {}
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *BasicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicResponse.Unmarshal(m, b)
}
func (m *BasicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicResponse.Marshal(b, m, deterministic)
}
func (m *BasicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicResponse.Merge(m, src)
}
func (m *BasicResponse) XXX_Size() int {
	return xxx_messageInfo_BasicResponse.Size(m)
}
func (m *BasicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BasicResponse proto.InternalMessageInfo

func (m *BasicResponse) GetResponse() int32 {
	if m != nil {
		return m.Response
	}
	return 0
}

type UserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserResponse struct {
	Response             map[string]int32 `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{15}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetResponse() map[string]int32 {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeMeta)(nil), "pb.NodeMeta")
	proto.RegisterType((*UpdateRequest)(nil), "pb.UpdateRequest")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*DeleteRequest)(nil), "pb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "pb.DeleteResponse")
	proto.RegisterType((*UpdateResponse)(nil), "pb.UpdateResponse")
	proto.RegisterType((*CacheRequest)(nil), "pb.CacheRequest")
	proto.RegisterType((*CacheResponse)(nil), "pb.CacheResponse")
	proto.RegisterType((*QueryRequest)(nil), "pb.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "pb.QueryResponse")
	proto.RegisterMapType((map[string]int32)(nil), "pb.QueryResponse.GroupMetasEntry")
	proto.RegisterType((*DumpRequest)(nil), "pb.DumpRequest")
	proto.RegisterType((*DumpResponse)(nil), "pb.DumpResponse")
	proto.RegisterType((*BasicRequest)(nil), "pb.BasicRequest")
	proto.RegisterType((*BasicResponse)(nil), "pb.BasicResponse")
	proto.RegisterType((*UserRequest)(nil), "pb.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "pb.UserResponse")
	proto.RegisterMapType((map[string]int32)(nil), "pb.UserResponse.ResponseEntry")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 718 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x9d, 0xc4, 0x4d, 0x27, 0x71, 0x7f, 0x56, 0x08, 0x4c, 0x84, 0x20, 0xb5, 0x84, 0x94,
	0x52, 0x29, 0x15, 0xe5, 0x82, 0x8a, 0x38, 0xd0, 0x16, 0x38, 0x00, 0x55, 0x49, 0xe9, 0x39, 0x5a,
	0xc7, 0xab, 0xb4, 0xa2, 0x89, 0x17, 0xaf, 0xdd, 0x2a, 0x4f, 0xc0, 0x85, 0xe7, 0xe0, 0x35, 0x78,
	0x17, 0x9e, 0x04, 0xcd, 0xec, 0xae, 0x63, 0xb7, 0x52, 0x49, 0x6f, 0xb3, 0x33, 0xb3, 0xdf, 0x7e,
	0x33, 0xdf, 0x8c, 0x0d, 0xbe, 0x12, 0xe9, 0xd5, 0xc5, 0x58, 0x0c, 0x64, 0x9a, 0x64, 0x09, 0x73,
	0x65, 0x14, 0xfe, 0x76, 0xa0, 0x75, 0x9c, 0xc4, 0xe2, 0x8b, 0xc8, 0x38, 0x63, 0xd0, 0x38, 0x4f,
	0x54, 0x16, 0x38, 0x3d, 0xa7, 0xbf, 0x3a, 0x24, 0x1b, 0x7d, 0x32, 0x49, 0xb3, 0xc0, 0xed, 0x39,
	0xfd, 0xe6, 0x90, 0x6c, 0xd6, 0x85, 0x56, 0xae, 0x44, 0x3a, 0xe3, 0x53, 0x11, 0xd4, 0x29, 0xb7,
	0x38, 0x63, 0x4c, 0x72, 0xa5, 0xae, 0x93, 0x34, 0x0e, 0x1a, 0x3a, 0x66, 0xcf, 0x6c, 0x03, 0xea,
	0x19, 0x9f, 0x04, 0x4d, 0x72, 0xa3, 0x89, 0xe8, 0x84, 0xe2, 0xe9, 0x17, 0x09, 0xe1, 0x01, 0x34,
	0x27, 0x69, 0x92, 0xcb, 0x60, 0x85, 0x9c, 0xfa, 0x10, 0xfe, 0x72, 0xc1, 0x3f, 0x93, 0x31, 0xcf,
	0xc4, 0x50, 0xfc, 0xc8, 0x85, 0xca, 0xd8, 0x63, 0x68, 0xc9, 0x3c, 0x1a, 0xd1, 0x7d, 0xcd, 0x78,
	0x45, 0xe6, 0xd1, 0x31, 0x42, 0x6c, 0x41, 0x07, 0x43, 0x05, 0x49, 0x97, 0xc2, 0x6d, 0x99, 0x47,
	0x67, 0x96, 0xe7, 0x23, 0xc0, 0xec, 0x91, 0xbc, 0x8e, 0x4d, 0x09, 0x9e, 0xcc, 0xa3, 0x93, 0xeb,
	0xd8, 0xc2, 0x52, 0xd1, 0x0d, 0x2a, 0x1a, 0x13, 0x4f, 0xb0, 0xee, 0x27, 0x00, 0x18, 0x22, 0x42,
	0x23, 0x53, 0x06, 0x26, 0x7f, 0x44, 0x87, 0x45, 0xc4, 0x0a, 0xbd, 0x02, 0xf1, 0x1b, 0x9f, 0xb0,
	0xe7, 0xb0, 0xc6, 0xf3, 0xec, 0x3c, 0x49, 0x2f, 0xb2, 0x39, 0x71, 0x32, 0x95, 0xf9, 0x85, 0x17,
	0x59, 0xb1, 0x1d, 0x80, 0x59, 0x12, 0x8b, 0xd1, 0x54, 0x64, 0x5c, 0x05, 0xad, 0x5e, 0xbd, 0xdf,
	0xde, 0xeb, 0x0c, 0x64, 0x34, 0xb0, 0xfa, 0x0c, 0x57, 0x67, 0xc6, 0x52, 0xe1, 0x07, 0x68, 0x0d,
	0x85, 0x92, 0xc9, 0x4c, 0x09, 0x6c, 0x22, 0x8f, 0xe3, 0xd4, 0xca, 0x86, 0x36, 0xb6, 0x7a, 0xaa,
	0x26, 0xa6, 0x70, 0x34, 0x17, 0x6d, 0xad, 0x97, 0xdb, 0x7a, 0x08, 0xfe, 0x91, 0xb8, 0x14, 0x8b,
	0xae, 0x3e, 0x04, 0x8f, 0x22, 0x2a, 0x70, 0x7a, 0x75, 0x2c, 0x42, 0x9f, 0x2a, 0x9a, 0xbb, 0x55,
	0xcd, 0xc3, 0x7d, 0x58, 0xb3, 0x20, 0x86, 0x52, 0x1f, 0x5a, 0xa9, 0xb1, 0x09, 0xc7, 0x54, 0x62,
	0xe3, 0xc3, 0x22, 0x8a, 0x77, 0xad, 0xac, 0xf7, 0xbe, 0xfb, 0x02, 0x3a, 0x87, 0x7c, 0x7c, 0x5e,
	0x70, 0x2f, 0x73, 0x74, 0x6e, 0x70, 0xdc, 0x01, 0xdf, 0xe4, 0x9a, 0x67, 0xba, 0x95, 0x67, 0x50,
	0xe7, 0x05, 0xf0, 0x27, 0xe8, 0x7c, 0xcd, 0x45, 0x3a, 0xb7, 0xc0, 0xcf, 0xa0, 0xad, 0x45, 0x47,
	0x28, 0xdb, 0x19, 0x20, 0x17, 0xce, 0xdb, 0xdd, 0xdd, 0xf9, 0xe3, 0x80, 0x6f, 0xd0, 0xcc, 0xd3,
	0x07, 0x16, 0x4e, 0x4b, 0xad, 0x8b, 0xdc, 0xc2, 0x22, 0x2b, 0x79, 0x03, 0x9a, 0x2b, 0xd2, 0xfb,
	0xfd, 0x2c, 0x4b, 0xe7, 0xe6, 0x45, 0x72, 0xdc, 0x98, 0x16, 0xf7, 0xce, 0x69, 0xe9, 0xbe, 0x85,
	0xf5, 0x1b, 0x58, 0x38, 0x20, 0xdf, 0xc5, 0xdc, 0xb4, 0x09, 0x4d, 0x1c, 0x90, 0x2b, 0x7e, 0x99,
	0x0b, 0xb3, 0xea, 0xfa, 0xb0, 0xef, 0xbe, 0x76, 0xc2, 0x6d, 0x68, 0x1f, 0xe5, 0x53, 0xb9, 0x4c,
	0x9b, 0x8f, 0xa0, 0xa3, 0x53, 0xff, 0xdf, 0x65, 0x16, 0xc0, 0xca, 0x54, 0x28, 0xc5, 0x27, 0xb6,
	0x67, 0xf6, 0x88, 0xc2, 0x1e, 0x70, 0x75, 0x31, 0x5e, 0x52, 0x58, 0x93, 0xbb, 0x84, 0xb0, 0xdb,
	0xd0, 0xc6, 0x5d, 0x5b, 0x06, 0xf7, 0xa7, 0x03, 0x1d, 0x9d, 0x6b, 0x70, 0xf7, 0x6f, 0xcd, 0xe5,
	0x53, 0xec, 0x77, 0x39, 0xa7, 0x18, 0x52, 0xad, 0x57, 0x91, 0xdf, 0x7d, 0x03, 0x7e, 0x25, 0x74,
	0x9f, 0xf6, 0xef, 0xfd, 0x75, 0x61, 0xf3, 0x54, 0xa4, 0x57, 0x22, 0x45, 0x6d, 0x4f, 0xf5, 0x37,
	0x9c, 0xed, 0x42, 0xe3, 0x73, 0xc2, 0x63, 0xb6, 0x49, 0x24, 0xca, 0x5f, 0xc6, 0x2e, 0x2b, 0xbb,
	0x4c, 0xe5, 0x35, 0x36, 0x80, 0x26, 0x8d, 0x17, 0xdb, 0x28, 0x4d, 0x9a, 0xbe, 0xb0, 0x79, 0x6b,
	0xf6, 0xc2, 0x1a, 0x7b, 0x09, 0x9e, 0xde, 0x6a, 0xfd, 0x44, 0xe5, 0x33, 0xa1, 0x9f, 0xa8, 0x2e,
	0x7d, 0x58, 0x63, 0x3b, 0xd0, 0x40, 0xf5, 0xd9, 0x3a, 0x45, 0x17, 0x23, 0xd3, 0xdd, 0x58, 0x38,
	0xca, 0x7c, 0x68, 0x23, 0x35, 0x9f, 0xf2, 0x22, 0x6b, 0x3e, 0x95, 0x75, 0x0d, 0x6b, 0x6c, 0x17,
	0xbc, 0x77, 0xe3, 0xb1, 0x50, 0x4a, 0x5f, 0x28, 0x0f, 0x88, 0xbe, 0x50, 0x19, 0x03, 0xcd, 0x86,
	0x3e, 0xac, 0xeb, 0x0b, 0x99, 0x4a, 0x6c, 0xca, 0xba, 0x85, 0xb5, 0xc8, 0xa3, 0x7f, 0xe2, 0xab,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x80, 0x62, 0x31, 0x24, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerNodeServiceClient is the client API for ServerNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerNodeServiceClient interface {
	Load(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (*DumpResponse, error)
	Cache(ctx context.Context, in *CacheRequest, opts ...grpc.CallOption) (*CacheResponse, error)
	Access(ctx context.Context, in *BasicRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type serverNodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewServerNodeServiceClient(cc *grpc.ClientConn) ServerNodeServiceClient {
	return &serverNodeServiceClient{cc}
}

func (c *serverNodeServiceClient) Load(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/pb.ServerNodeService/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverNodeServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/pb.ServerNodeService/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverNodeServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/pb.ServerNodeService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverNodeServiceClient) Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (*DumpResponse, error) {
	out := new(DumpResponse)
	err := c.cc.Invoke(ctx, "/pb.ServerNodeService/Dump", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverNodeServiceClient) Cache(ctx context.Context, in *CacheRequest, opts ...grpc.CallOption) (*CacheResponse, error) {
	out := new(CacheResponse)
	err := c.cc.Invoke(ctx, "/pb.ServerNodeService/Cache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverNodeServiceClient) Access(ctx context.Context, in *BasicRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, "/pb.ServerNodeService/Access", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverNodeServiceClient) User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/pb.ServerNodeService/User", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerNodeServiceServer is the server API for ServerNodeService service.
type ServerNodeServiceServer interface {
	Load(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Dump(context.Context, *DumpRequest) (*DumpResponse, error)
	Cache(context.Context, *CacheRequest) (*CacheResponse, error)
	Access(context.Context, *BasicRequest) (*BasicResponse, error)
	User(context.Context, *UserRequest) (*UserResponse, error)
}

// UnimplementedServerNodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServerNodeServiceServer struct {
}

func (*UnimplementedServerNodeServiceServer) Load(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (*UnimplementedServerNodeServiceServer) Query(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedServerNodeServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedServerNodeServiceServer) Dump(ctx context.Context, req *DumpRequest) (*DumpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dump not implemented")
}
func (*UnimplementedServerNodeServiceServer) Cache(ctx context.Context, req *CacheRequest) (*CacheResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cache not implemented")
}
func (*UnimplementedServerNodeServiceServer) Access(ctx context.Context, req *BasicRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Access not implemented")
}
func (*UnimplementedServerNodeServiceServer) User(ctx context.Context, req *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User not implemented")
}

func RegisterServerNodeServiceServer(s *grpc.Server, srv ServerNodeServiceServer) {
	s.RegisterService(&_ServerNodeService_serviceDesc, srv)
}

func _ServerNodeService_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerNodeServiceServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerNodeService/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerNodeServiceServer).Load(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerNodeService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerNodeServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerNodeService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerNodeServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerNodeService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerNodeServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerNodeService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerNodeServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerNodeService_Dump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerNodeServiceServer).Dump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerNodeService/Dump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerNodeServiceServer).Dump(ctx, req.(*DumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerNodeService_Cache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerNodeServiceServer).Cache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerNodeService/Cache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerNodeServiceServer).Cache(ctx, req.(*CacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerNodeService_Access_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerNodeServiceServer).Access(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerNodeService/Access",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerNodeServiceServer).Access(ctx, req.(*BasicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerNodeService_User_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerNodeServiceServer).User(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServerNodeService/User",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerNodeServiceServer).User(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerNodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ServerNodeService",
	HandlerType: (*ServerNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Load",
			Handler:    _ServerNodeService_Load_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _ServerNodeService_Query_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ServerNodeService_Delete_Handler,
		},
		{
			MethodName: "Dump",
			Handler:    _ServerNodeService_Dump_Handler,
		},
		{
			MethodName: "Cache",
			Handler:    _ServerNodeService_Cache_Handler,
		},
		{
			MethodName: "Access",
			Handler:    _ServerNodeService_Access_Handler,
		},
		{
			MethodName: "User",
			Handler:    _ServerNodeService_User_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
